### PR TITLE
adding PVC storage and updating readme

### PR DESCRIPTION
**Pull request by memodi**
Follow up to PR #29 .
I've used some arbitrary high values for storage and replicas. Also, recommending to use cluster default StorageClass instead of specific such as gp2 which I've found to be useful across different cluster versions and cloud providers. 

@jotak please review.

### CODE REVIEW

**Comment by jotak** [comment]
This would break the make scripts in the operator so we need to update it as well: https://github.com/netobserv/network-observability-operator/blob/main/.mk/development.mk#L48-L66

**Comment by memodi** [comment]
thanks, created this PR for  updated make targets: https://github.com/netobserv/network-observability-operator/pull/174

**Review by jotak — APPROVED** [review]
thanks!

**Comment by memodi** [comment]
@jotak - FYI, I added config in [7e7a5bc](https://github.com/netobserv/documents/pull/30/commits/7e7a5bc7c2ec0f4517f61df652d6135106739a09) since I was running into an issue with AMQ Streams Operator, where the topic was auto created and it overwrites the topic config.

**Pull request merged**
