### PR TITLE
NETOBSERV-547 Tweak loki config

### PR DESCRIPTION
**Pull request by jpinsonneau**
Here is a non exhaustive list of errors with related tweaks you may apply.

We can try to better define some default values according to cluster sizes or flow processed per second in a table format in followup.

### CODE REVIEW

**Comment by eranra** [comment]
@nathan-weinberg this answers a lot of the questions around (run without limits)

@jpinsonneau this is great info

**Comment by eranra** [comment]
@jpinsonneau what about automation of all of those ... can we somehow "do" that --- maybe create a script to run over the operator that we add in the instructions for customers?

**Comment by jpinsonneau** [comment]
> @jpinsonneau what about automation of all of those ... can we somehow "do" that --- maybe create a script to run over the operator that we add in the instructions for customers?

For loki simple / distributed it's easy to integrate these in the provided config. I'll double check these but we are in a good shape for now.
We decided to take more time for `loki-operator` as it needs parameters defined in their CRD. I wonder if we can do something more flexible to allow any config without having a huge CRD on their side.

**Comment by jpinsonneau** [comment]
> Thanks for this @jpinsonneau - please add details as to how/where to change these configs (i.e. the `kubectl` or `oc` commands) as well

Sure I can document this for each situations: simple / distributed / loki-operator

**Comment by jpinsonneau** [comment]
> Thanks for this @jpinsonneau - please add details as to how/where to change these configs (i.e. the `kubectl` or `oc` commands) as well

Here we go https://github.com/netobserv/documents/pull/39/commits/dee092b819e0d450895031444a7951e8dc1802ff @nathan-weinberg

**Review by nathan-weinberg — APPROVED** [review]
/lgtm

**Pull request merged**
