### PR TITLE
NETOBSERV-374 - Improve the 0-click Loki install

### PR DESCRIPTION
**Pull request by jpinsonneau**
Following our [Jira discussion](https://issues.redhat.com/browse/NETOBSERV-374) we can load credentials from secret mounted as environment variable and injected in the loki config.

### CODE REVIEW

**Review by jotak — APPROVED** [review]
lgtm
decoupling secret allows the user to have a more secure setup with vaults or sealed secrets

**Comment by memodi** [comment]
@jpinsonneau - my initial concern was if the cluster is shared with same type of access, users can still view secrets for e.g.: by way of commands such as `oc get secret/loki-distributed -o yaml`

if there's no other better alternative then I guess we can create a new IAM user with restrictive policies and not use personal access_id and access_key.

**Comment by jpinsonneau** [comment]
> if there's no other better alternative then I guess we can create a new IAM user with restrictive policies and not use personal access_id and access_key.

Yes I also came to that point. As soon as you have access to secret / pod terminal, I don't see solution to keep these config safe.

**Comment by jpinsonneau** [comment]
sure, thanks for the feedback @jotak & @memodi

**Pull request merged**
