### PR TITLE
Add kafka-tls example yaml

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
LGTM

Side question, once we will have kafka TLS working, do you see any disadvantage to only keep this one and removing the kafka config without TLS?

**Comment by jpinsonneau** [comment]
Works fine on my side :+1: Can you add a mention of the new files in `kafka.md` ? 

Also, since the `kafka-cluster.yaml` & `kafka-tls.yaml` are almost the same, we should consider splitting the yaml and put `ConfigMap` and `PodMonitor` in a separate file. We can have a folder and apply bunch of files at once as same as `distributed-loki`.

**Review by mariomac — COMMENTED** [review]
It seems to work. Does it use any cluster internal certificate authority to use internally trusted certificates, or should I just skip key verification in my kafka clients?

**Comment by jotak** [comment]
@jpinsonneau I've reorganized the kafka files. Also in kafka.md, removed old mentions of usage with kube-enricher/goflow2
and added some mentions of `kfk`, the strimzi CLI

**Comment by jotak** [comment]
just updated kowl doc/chart as well

**Pull request merged**
